# Generated by Django 5.2.4 on 2025-07-23 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('organizador_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('empresa', 'Empresa'), ('institucion', 'Institucion')], default='individual', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('evento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('inicio', models.DateTimeField()),
                ('duracion_en_minutos', models.PositiveIntegerField(help_text='Duración en minutos.')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('categorias', models.ManyToManyField(to='eventos.categoria')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.organizador')),
            ],
        ),
    ]
