# Generated by Django 5.2.4 on 2025-08-05 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('autor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('noticia_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=85)),
                ('subtitulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.autor')),
                ('categorias', models.ManyToManyField(to='noticias.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('imagen_id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='noticias/imagenes/')),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='noticias.noticia')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.noticia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('url_video', models.URLField(max_length=500)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='noticias.noticia')),
            ],
        ),
    ]
