# Generated by Django 5.2.5 on 2025-08-08 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='fecha_publicacion',
            new_name='fecha',
        ),
    ]
