# Generated by Django 5.2.4 on 2025-08-05 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('imagen_id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='noticias/imagenes/')),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='noticias.noticia')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('url_video', models.URLField(max_length=500)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='noticias.noticia')),
            ],
        ),
    ]
