# Generated by Django 5.2.4 on 2025-08-05 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_comentario_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('biografia', models.TextField()),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='noticias.persona')),
            ],
        ),
    ]
