# Generated by Django 5.2.4 on 2025-08-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_imagen_video'),
        ('noticias', '0003_perfil'),
    ]

    operations = [
    ]
