# Generated by Django 5.2.4 on 2025-08-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_noticia_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='archivo_video',
            field=models.FileField(blank=True, null=True, upload_to='noticias/videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url_video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
